#!/bin/sh
##
## $Id$
##

PROGNAME=`basename "$0"`
DIRNAME=`dirname "$0"`

warn() {
    echo "${PROGNAME}: $*"
}

die() {
    warn "$*"
    exit 1
}

clean() {
    echo "Cleaning..."
    
    rm -rf ~/.m2/repository/org/apache/geronimo/genesis
    
    for x in `find "$DIRNAME" -name target -type d`; do
        rm -rf "$x"
    done
}

main() {
    clean
    
    "$DIRNAME/build"
    
    echo "Done"
}

main | 2>&1 tee bootstrap.log
