#!/bin/sh
##
## $Id$
##

PROGNAME=`basename "$0"`
DIRNAME=`dirname "$0"`

warn() {
    echo "${PROGNAME}: $*"
}

die() {
    warn "$*"
    exit 1
}

clean() {
    echo "Cleaning..."
    
    rm -rf ~/.m2/repository/org/apache/geronimo/genesis
    
    find "$DIRNAME" -name target -type d -exec rm -rf \{\} \;
}

clean

"$DIRNAME/build"

echo "Done"

